title: Leetcode solutions by tgic
email: farmer1992@gmail.com
description: "Leetcode solutions by tgic"
github_username:  tg123
markdown: redcarpet

redcarpet:
  extensions: ['highlight', 'autolink']

highlighter: pygments
